theme: jekyll-theme-cayman
title: Analisi sentiment e incasso dei film
description: <p>Un'analisi del grado di correlazione tra Sentiment e Incasso</p><small>Progetto a cura di: Caterina Pisani, Alessandro Pontini, Federico De Servi e Francesco Simoncelli.</small>
