theme: jekyll-theme-cayman
title: Analisi sentiment e incasso dei film
description: [<p>Analisi del grado di correlazione tra Sentiment e Incasso<p><small>Progetto a cura di: Caterina Pisani<small>,</small> Alessandro Pontini , Federico De Servi e Francesco Simoncelli</small>]
