theme: jekyll-theme-cayman
title: Analisi sentiment e incasso dei film
description: [<p>Analisi del grado di correlazione tra Sentiment e Incasso per alcuni film USA<p><small>Progetto a cura di&#58; Caterina Pisani&#44; Alessandro Pontini&#44; Federico De Servi e Francesco Simoncelli</small>]
